query products ($name: String) {
    products(options: { filter: { name: { contains: $name } } }) {
        items {
        name
        description
        featuredAsset{
            source
            }
        }
    }
}

